theme: jekyll-theme-cayman
title: Research on Frequency Converter
author: Frank Lee
email: franklee@umail.ucsb.edu
description: Research on high frequency sound converter
github_username:  franklee26

header_pages:
  - README.md
markdown: kramdown
