theme: jekyll-theme-cayman
title: QEmbed
author: Frank Lee
email: franklee@ucsb.edu
description: A simple Python package for approaching various embedding problems in Quantum Annealing research.
github_username:  franklee26

header_pages:
  - README.md
  - somepage.md
markdown: kramdown
