theme: jekyll-theme-cayman
title: QEmbed
author: Frank Lee
email: franklee@ucsb.edu
description: Approaches on various embedding problems for Quantum Annealing
github_username:  franklee26

header_pages:
  - README.md
markdown: kramdown
